api/urls.py
from django.urls import path
from .views import *

app_name = 'api'

urlpatterns = [
    path('article_list', Articlelist.as_view(), name='articlelist'),
    path('article_detail/<int:pk>', ArticleDetail.as_view(), name='articledetail'),
    path('user_list', Userlist.as_view(), name='userlist'),
    path('user_detail/<int:pk>', UserDetail.as_view(), name='userdetail')

]

blog/urls.py
from django.urls import path
from .views import *

app_name='article'


urlpatterns=[
    path('article_list',ArticleList.as_view(),name='articlelist'),
    path('detail/<int:pk>/',ArticleDetail.as_view(),name='articledetail'),
    path('list',UserList.as_view(),name='user_list'),
    path('detail/<int:pk>',UserDetail.as_view(),name='user_detail')
]

drfcourse/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('',include('home.urls')),
    path('blog/',include('blog.urls')),
    path('api/',include('api.urls'))
]

home/urls.py
from django.urls import path
from .views import HomePage

app_name='home'

urlpatterns=[
    path('',HomePage.as_view(),name='home_page')
]

api/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.

class Article(models.Model):
    title=models.CharField(max_length=25)
    slug=models.SlugField()
    author=models.ForeignKey(User,on_delete=models.CASCADE)
    body=models.TextField()
    published=models.DateTimeField(default=timezone.now)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    status=models.BooleanField(default=False)


    def __str__(self):
        return self.title

home/models.py
from django.db import models

# Create your models here.

api/views.py
from .Serializer import ArticleSerializers,UserSerializers
from blog.models import Article
from .permission import *
from rest_framework.generics import ListCreateAPIView,RetrieveDestroyAPIView
from  django.contrib.auth.models import User
class Articlelist(ListCreateAPIView):
    queryset = Article.objects.all()
    serializer_class = ArticleSerializers

class ArticleDetail(RetrieveDestroyAPIView):
    queryset = Article.objects.all()
    serializer_class = ArticleSerializers
    permission_classes = (IsStaffOrReadOnly,IsAuthorOrReadOnly)

class Userlist(ListCreateAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializers
    permission_classes = (IsSuperUserOrStaffReadOnly,)


class UserDetail(RetrieveDestroyAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializers
    permission_classes = (IsSuperUserOrStaffReadOnly,)



# Create your views here.

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from .models import Article
from django.contrib.auth.models import User


class ArticleList(ListView):
    model = Article
    template_name = 'blog/article_list.html'

class ArticleDetail(DetailView):
    model = Article
    template_name = 'blog/articledetail.html'

class UserList(ListView):
    model = User
    template_name = 'blog/userlist.html'


class UserDetail(DetailView):
    model = User
    template_name = 'blog/userdetail.html'



# Create your views here.

home/views.py
from django.shortcuts import render
from django.views.generic import View


class HomePage(View):
    def get(self, requset):
         return render(requset, 'home/home.html', context={})

# Create your views here.

blog/templates/blog/article_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Article_List</title>
</head>
<body>
{% for article in object_list %}
    <h1><a href="{% url 'article:articledetail' article.pk %}">{{ article.title }}</a></h1>
    <h1><a href="{% url 'api:articledetail' article.pk %}">drf {{ article.title }}</a></h1>
    <h1>{{ article.author }}</h1>
    <h2>{{ article.body }}</h2>
    <h3>{{ article.published }}</h3>
    <hr>
{% endfor%}

<h1><a href="{% url 'home:home_page' %}">HomePage</a></h1>

</body>
</html>

blog/templates/blog/articledetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Article_Detail</title>
</head>
<body>
<h1>{{ object.title }}</h1>
<h1>{{ object.author }}</h1>
<h2>{{ object.body }}</h2>
<h3>{{ object.published }}</h3>
<hr>
<h1><a href="{% url 'home:home_page' %}">HomePage</a></h1>

</body>
</html>

blog/templates/blog/userdetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>UserDetail</title>
</head>
<body>
<h1>{{ object.username }}</h1>
<h1>{{ object.email }}</h1>
<h2>{{ object.last_login }}</h2>
<h3>{{ object.pk }}</h3>
<hr>
<h1><a href="{% url 'home:home_page' %}">HomePage</a></h1>
</body>
</html>

blog/templates/blog/userlist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Userlist</title>
</head>
<body>
{% for user in object_list %}
    <h1><a href="{% url 'article:user_detail' user.pk %}">{{ user.username }}</a></h1>
    <h1><a href="{% url 'api:userdetail' user.pk %}">drf {{ user.username }}</a></h1>
    <h1>{{ user.get_full_name }}</h1>
    <h2>{{user.date_joined }}</h2>
    <h3>{{ user.email }}</h3>
    <hr>
{% endfor%}

<h1><a href="{% url 'home:home_page' %}">HomePage</a></h1>
</body>
</html>

home/templates/home/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>HomePage</title>
</head>
<body>

<h1 style="color:navy" class="text-center">HomePage</h1>
<h1><a href="{% url 'article:articlelist' %}" class="text-center">articlelist</a></h1>
<h2><a style="color: green" href="{% url 'api:articlelist' %}" class="fa-align-center">articlelist</a>
</h2>
<div class="text-center">
    <h5><a href="{% url 'api:userlist' %}" class="text-center">Userlist</a></h5>
</div>
<div class="text-center">
    <h5><a href="{% url 'article:user_list' %}" style="color: #0a6c04" class="text-center">UserList</a></h5>
</div>

</body>
</html>